### ISSUE TITLE
TypeError: NotificationEventHandlers[eventType] is undefined

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [dynilath/BCNotifyPlus#1]
Seems the mod is broken and isn't notifying people when it is triggered. According to the error log it is something to do with `NotificationEventHandlers[eventType]` being undefined.

I am guessing club updated some background functions/code, which thus broke this.

The game gets sorta buggy with things not responding once it happens such as potentially the WCE instant messenger breaking etc.

**Comment by dynilath** [comment]
Fixed in b889186
